project_id = "nmwrplxnjqyerorbbcxk"

[functions.manage-users]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.analisar-folha]
verify_jwt = false

[functions.notificar-feriados-proximo-mes]
verify_jwt = false
