import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, CheckCircle2, Clock3, Plus, Search, UserPlus } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Modal } from "@/components/ui/Modal";
import { createAdmission, getAdmissions, getOrganizations } from "@/lib/api";
import { stepLabels, stepOrder } from "@/features/workflows/workflow-ui";
import { formatCpf, formatPhone, isValidCpf, isValidPhone, normalizeDigits } from "@/lib/cnpj";

const emptyForm = { candidateName:"",email:"",phone:"",cpf:"",companyId:"company_flux",companyName:"Grupo Flux",establishmentName:"Matriz São Paulo",departmentName:"Pessoas e Cultura",position:"",managerName:"Marina Alves",expectedStartDate:"2026-09-01",salary:0 };
export function AdmissionsPage() {
  const navigate=useNavigate(); const client=useQueryClient(); const {data=[]}=useQuery({queryKey:["admissions"],queryFn:getAdmissions}); const {data:org}=useQuery({queryKey:["organizations"],queryFn:getOrganizations});
  const [query,setQuery]=useState(""); const [open,setOpen]=useState(false); const [form,setForm]=useState(emptyForm);
  const mutation=useMutation({mutationFn:createAdmission,onSuccess:item=>{client.invalidateQueries({queryKey:["admissions"]});client.invalidateQueries({queryKey:["workflow-overview"]});setOpen(false);navigate(`/admissoes/${item.id}`)}});
  const filtered=useMemo(()=>data.filter(x=>`${x.candidateName} ${x.position} ${x.companyName}`.toLowerCase().includes(query.toLowerCase())),[data,query]);
  const submit=(event:FormEvent)=>{event.preventDefault();if(isValidCpf(form.cpf)&&isValidPhone(form.phone))mutation.mutate({...form,cpf:normalizeDigits(form.cpf),phone:normalizeDigits(form.phone)})};
  return <div className="page"><section className="simple-heading"><div><span className="eyebrow"><UserPlus size={15}/> Jornada de entrada</span><h1>Admissões</h1><p>Da solicitação ao primeiro dia, com acompanhamento somente por exceção.</p></div><button className="primary-button" onClick={()=>setOpen(true)}><Plus size={17}/> Nova admissão</button></section>
    <section className="admission-stats"><div><strong>{data.filter(x=>x.status==="running").length}</strong><span><Clock3/> Em andamento</span></div><div><strong>{data.filter(x=>x.status==="completed").length}</strong><span><CheckCircle2/> Concluídas</span></div><div><strong>{Math.round(data.reduce((sum,x)=>sum+x.progress,0)/Math.max(data.length,1))}%</strong><span>Progresso médio</span></div></section>
    <section className="panel admission-board"><div className="table-toolbar"><div className="field"><Search size={17}/><input placeholder="Buscar candidato, cargo ou empresa" value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filtered.length} processos</span></div><div className="admission-cards">{filtered.map(item=><Link className="admission-card" to={`/admissoes/${item.id}`} key={item.id}><header><span className="person-avatar" style={{background:item.status==="completed"?"#17a673":"#155eef"}}>{item.candidateName.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><div><h2>{item.candidateName}</h2><p>{item.position} · {item.companyName}</p></div><ArrowRight/></header><div className="mini-stepper">{stepOrder.map((step,index)=><i key={step} className={item.status==="completed"||index<=stepOrder.indexOf(item.currentStep)?"done":""}/>)}</div><div className="admission-card-meta"><span><small>Etapa atual</small><strong>{item.status==="completed"?"Concluído":stepLabels[item.currentStep]}</strong></span><span><small>Início previsto</small><strong>{new Date(`${item.expectedStartDate}T12:00:00`).toLocaleDateString("pt-BR")}</strong></span><b>{item.progress}%</b></div></Link>)}</div></section>
    <Modal open={open} onClose={()=>setOpen(false)} title="Iniciar nova admissão" description="O FluxRH criará todas as etapas, tarefas e prazos automaticamente."><form className="form-grid" onSubmit={submit}><label className="span-2">Nome completo<input required value={form.candidateName} onChange={e=>setForm({...form,candidateName:e.target.value})}/></label><label>E-mail<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Telefone<input required inputMode="tel" maxLength={15} placeholder="(00) 00000-0000" value={form.phone} onChange={e=>setForm({...form,phone:formatPhone(e.target.value)})}/></label><label>CPF<input required inputMode="numeric" maxLength={14} placeholder="000.000.000-00" value={form.cpf} onChange={e=>setForm({...form,cpf:formatCpf(e.target.value)})}/></label><label>Empresa<select value={form.companyId} onChange={e=>{const company=org?.companies.find(x=>x.id===e.target.value);setForm({...form,companyId:e.target.value,companyName:company?.tradeName??""})}}>{org?.companies.map(x=><option key={x.id} value={x.id}>{x.tradeName}</option>)}</select></label><label>Cargo<input required value={form.position} onChange={e=>setForm({...form,position:e.target.value})}/></label><label>Gestor<input required value={form.managerName} onChange={e=>setForm({...form,managerName:e.target.value})}/></label><label>Salário<input type="number" min="1" required value={form.salary||""} onChange={e=>setForm({...form,salary:Number(e.target.value)})}/></label><label>Início previsto<input type="date" required value={form.expectedStartDate} onChange={e=>setForm({...form,expectedStartDate:e.target.value})}/></label><footer className="form-actions span-2"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button" disabled={mutation.isPending||!isValidCpf(form.cpf)||!isValidPhone(form.phone)}>{mutation.isPending?"Iniciando...":"Iniciar workflow"}</button></footer></form></Modal>
  </div>;
}
