import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ArrowRight, Bot, Check, CheckCircle2, CircleAlert, Clock3, FileCheck2, FileSignature, FileText, PlayCircle, Sparkles, TriangleAlert, UserCheck, UserRound } from "lucide-react";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { advanceAdmission, createWorkflowException, getAdmission } from "@/lib/api";
import { Modal } from "@/components/ui/Modal";
import { stepLabels, stepOrder } from "@/features/workflows/workflow-ui";
import { formatCpf, formatPhone, normalizeDigits } from "@/lib/cnpj";

export function AdmissionDetailPage() {
  const {id=""}=useParams(); const client=useQueryClient(); const [exceptionOpen,setExceptionOpen]=useState(false);const [exception,setException]=useState({title:"",description:"",priority:"medium" as "critical"|"high"|"medium"|"low"}); const {data:item,isLoading}=useQuery({queryKey:["admission",id],queryFn:()=>getAdmission(id)});
  const mutation=useMutation({mutationFn:()=>advanceAdmission(id),onSuccess:data=>{client.setQueryData(["admission",id],data);client.invalidateQueries({queryKey:["admissions"]});client.invalidateQueries({queryKey:["workflow-overview"]})}});
  const exceptionMutation=useMutation({mutationFn:()=>createWorkflowException(id,exception),onSuccess:()=>{client.invalidateQueries({queryKey:["admission",id]});client.invalidateQueries({queryKey:["workflow-exceptions"]});setExceptionOpen(false);setException({title:"",description:"",priority:"medium"})}});
  if(isLoading||!item)return <div className="page"><div className="page-skeleton"/></div>;
  const currentIndex=stepOrder.indexOf(item.currentStep); const pending=item.tasks.filter(x=>x.stepKey===item.currentStep&&x.status!=="completed");
  return <div className="page admission-detail"><Link className="back-link" to="/admissoes"><ArrowLeft size={16}/> Voltar para admissões</Link>
    <section className="admission-hero panel"><div className="profile-main"><span className="large-avatar" style={{background:item.status==="completed"?"#17a673":"#155eef"}}>{item.candidateName.split(" ").map(x=>x[0]).slice(0,2).join("")}</span><div><div className="profile-title"><h1>{item.candidateName}</h1><StatusBadge tone={item.status==="exception"?"red":item.status==="completed"?"green":"blue"}>{item.status==="exception"?"Com exceção":item.status==="completed"?"Concluída":"Em andamento"}</StatusBadge></div><p>{item.position} · {item.companyName}</p><small>Workflow #{item.id.slice(-8)} · definição v{item.definitionVersion}</small></div></div><div className="hero-progress"><span><small>Progresso geral</small><strong>{item.progress}%</strong></span><div className="progress"><i style={{width:`${item.progress}%`}}/></div><button className="secondary-button" onClick={()=>setExceptionOpen(true)} disabled={item.status==="completed"}><TriangleAlert size={16}/> Registrar exceção</button></div></section>
    <section className="process-stepper">{stepOrder.map((step,index)=><div className={`${index<currentIndex||item.status==="completed"?"completed":""} ${index===currentIndex&&item.status!=="completed"?"current":""}`} key={step}><span>{index<currentIndex||item.status==="completed"?<Check/>:index+1}</span><strong>{stepLabels[step]}</strong>{index<stepOrder.length-1&&<i/>}</div>)}</section>
    <div className="admission-detail-grid"><main className="admission-main"><StagePanel item={item}/><section className="panel current-tasks"><div className="panel-heading"><div><span className="section-label"><Clock3 size={13}/> Trabalho da etapa</span><h2>Tarefas e automações</h2></div><span className="count-pill">{pending.length} pendentes</span></div>{item.tasks.filter(x=>x.stepKey===item.currentStep).map(task=><div className="workflow-task" key={task.id}><span className={`task-check ${task.status==="completed"?"done":""}`}>{task.status==="completed"?<Check/>:task.kind==="automatic"?<Bot/>:<UserRound/>}</span><div><strong>{task.title}</strong><p>{task.description}</p><small>{task.kind==="automatic"?"Automática":task.kind==="approval"?"Aprovação":"Humana"} · {task.assignee}</small></div><StatusBadge tone={task.status==="completed"?"green":"amber"}>{task.status==="completed"?"Concluída":"Pendente"}</StatusBadge></div>)}{item.status!=="completed"&&<footer className="advance-footer"><div><Sparkles/><span><strong>Pronto para avançar</strong><small>Ao confirmar, o motor concluirá tarefas e preparará a próxima etapa.</small></span></div><button className="primary-button" onClick={()=>mutation.mutate()} disabled={mutation.isPending}>{mutation.isPending?"Processando...":currentIndex===stepOrder.length-1?"Concluir admissão":"Concluir etapa e avançar"}<ArrowRight size={16}/></button></footer>}</section></main>
      <aside className="admission-aside"><section className="panel candidate-info"><h2>Dados da contratação</h2><Info label="CPF" value={normalizeDigits(item.cpf).length===11?formatCpf(item.cpf):item.cpf}/><Info label="E-mail" value={item.email}/><Info label="Telefone" value={[10,11].includes(normalizeDigits(item.phone).length)?formatPhone(item.phone):item.phone}/><Info label="Gestor" value={item.managerName}/><Info label="Início previsto" value={new Date(`${item.expectedStartDate}T12:00:00`).toLocaleDateString("pt-BR")}/><Info label="Prazo do processo" value={new Date(item.dueAt).toLocaleDateString("pt-BR")}/></section><section className="panel admission-history"><h2>Histórico</h2>{item.history.map(event=><div key={event.id}><i className={event.type}/><span><strong>{event.title}</strong><p>{event.description}</p><small>{event.actor} · {new Date(event.occurredAt).toLocaleString("pt-BR")}</small></span></div>)}</section></aside>
    </div><Modal open={exceptionOpen} onClose={()=>setExceptionOpen(false)} title="Registrar exceção" description="O workflow ficará sinalizado até a decisão ser registrada."><form className="form-grid" onSubmit={event=>{event.preventDefault();exceptionMutation.mutate()}}><label className="span-2">Título<input required minLength={3} value={exception.title} onChange={e=>setException({...exception,title:e.target.value})}/></label><label className="span-2">Descrição<textarea required minLength={3} value={exception.description} onChange={e=>setException({...exception,description:e.target.value})}/></label><label>Prioridade<select value={exception.priority} onChange={e=>setException({...exception,priority:e.target.value as typeof exception.priority})}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select></label><footer className="form-actions span-2"><button type="button" className="secondary-button" onClick={()=>setExceptionOpen(false)}>Cancelar</button><button className="primary-button" disabled={exceptionMutation.isPending}>{exceptionMutation.isPending?"Registrando…":"Registrar exceção"}</button></footer></form></Modal>
  </div>;
}

function StagePanel({item}:{item:NonNullable<Awaited<ReturnType<typeof getAdmission>>>}) {
  if(item.status==="completed")return <section className="panel completion-banner"><span><CheckCircle2/></span><div><small>PROCESSO CONCLUÍDO</small><h2>Admissão pronta para o primeiro dia</h2><p>Documentos, validações, contrato e onboarding foram concluídos com trilha de auditoria.</p></div></section>;
  if(item.currentStep==="digital_admission")return <section className="panel stage-panel"><StageHeader icon={PlayCircle} eyebrow="Etapa 1" title="Admissão digital" description="Valide a solicitação, os dados da vaga e o início previsto."/><div className="validation-grid"><Validation label="Dados pessoais recebidos" done/><Validation label="Cargo e salário definidos" done/><Validation label="Lotação confirmada" done/><Validation label="Aprovação do RH"/></div></section>;
  if(item.currentStep==="documents")return <section className="panel stage-panel"><StageHeader icon={FileText} eyebrow="Etapa 2" title="Coleta de documentos" description="O portal acompanha os envios e cobra automaticamente o que faltar."/><div className="document-list">{item.documents.map(doc=><div key={doc.id}><span className="doc-icon"><FileText/></span><span><strong>{doc.name}</strong><small>{doc.required?"Obrigatório":"Opcional"}</small></span><StatusBadge tone={doc.status==="valid"?"green":doc.status==="rejected"?"red":doc.status==="received"?"blue":"amber"}>{doc.status==="requested"?"Solicitado":doc.status==="received"?"Recebido":doc.status==="valid"?"Validado":"Rejeitado"}</StatusBadge></div>)}</div></section>;
  if(item.currentStep==="validation")return <section className="panel stage-panel"><StageHeader icon={FileCheck2} eyebrow="Etapa 3" title="Validação automática" description="O FluxRH confere consistência, duplicidades e requisitos antes do contrato."/><div className="validation-list">{item.validations.map(check=><div key={check.id}><span className={check.status}><FileCheck2/></span><div><strong>{check.label}</strong><small>{check.detail}</small></div><StatusBadge tone={check.status==="approved"?"green":check.status==="attention"?"red":"amber"}>{check.status==="approved"?"Aprovado":check.status==="attention"?"Atenção":"Pendente"}</StatusBadge></div>)}</div></section>;
  if(item.currentStep==="contract")return <section className="panel stage-panel contract-stage"><StageHeader icon={FileSignature} eyebrow="Etapa 4" title="Contrato e aceite" description="Gere o documento com a regra vigente e acompanhe o aceite eletrônico."/><div className="contract-preview"><span><FileSignature/></span><div><strong>Contrato de trabalho · {item.candidateName}</strong><p>Modelo CLT padrão · definição v{item.definitionVersion}</p><small>{item.contract.status==="not_generated"?"Aguardando geração":item.contract.status==="generated"?"Gerado e pronto para envio":item.contract.status==="sent"?"Enviado para aceite":"Aceito eletronicamente"}</small></div><Link className="secondary-button" to={`/documentos?workflow=${item.id}`}>Abrir documentos</Link></div></section>;
  return <section className="panel stage-panel"><StageHeader icon={UserCheck} eyebrow="Etapa 5" title="Onboarding" description="Prepare o primeiro dia, os responsáveis e o acompanhamento da experiência."/><div className="onboarding-progress"><div><span><strong>{item.onboarding.checklistCompleted}/{item.onboarding.checklistTotal}</strong><small>Tarefas concluídas</small></span><div className="progress"><i style={{width:`${item.onboarding.checklistCompleted/item.onboarding.checklistTotal*100}%`}}/></div></div><div><UserCheck/><span><small>Responsável de apoio</small><strong>{item.onboarding.buddy??"A definir"}</strong></span></div></div></section>;
}
function StageHeader({icon:Icon,eyebrow,title,description}:{icon:typeof FileText;eyebrow:string;title:string;description:string}){return <div className="stage-header"><span><Icon/></span><div><small>{eyebrow}</small><h2>{title}</h2><p>{description}</p></div></div>}
function Validation({label,done=false}:{label:string;done?:boolean}){return <div className={done?"done":""}><span>{done?<Check/>:<CircleAlert/>}</span><strong>{label}</strong></div>}
function Info({label,value}:{label:string;value:string}){return <div className="candidate-info-row"><small>{label}</small><strong>{value}</strong></div>}

