import type{CreateDocumentRequestInput,DocumentOverview,DocumentRecord}from"@fluxrh/contracts";
import type{SupabaseClient}from"@supabase/supabase-js";
import{genericPreview,type DocumentsRepository}from"./documents.repository.js";
type DocumentRow={id:string;workflow_id:string|null;employee_id:string|null;subject_name:string;subject_document:string;company_name:string;title:string;category:DocumentRecord["category"];status:DocumentRecord["status"];template_id:string|null;template_name:string|null;version:number;required:boolean;preview:DocumentRecord["preview"];expires_at:string|null;validation_note:string|null;created_at:string;updated_at:string};
type AcceptanceRow={id:string;document_id:string;signer_name:string;signer_document:string;accepted_at:string;ip_address:string;user_agent:string;document_hash:string;document_version:number;method:"authenticated_acceptance"|"confirmation_code";statement:string};type EventRow={id:string;document_id:string;action:string;detail:string;actor:string;actor_type:"system"|"user"|"signer";occurred_at:string};
export class SupabaseDocumentsRepository implements DocumentsRepository{
 constructor(private client:SupabaseClient){}
 private async all(id?:string):Promise<DocumentRecord[]>{let query=this.client.from("documents").select("id,workflow_id,employee_id,subject_name,subject_document,company_name,title,category,status,template_id,template_name,version,required,preview,expires_at,validation_note,created_at,updated_at").order("updated_at",{ascending:false});if(id)query=query.eq("id",id);const documentsResult=await query;if(documentsResult.error)throw new Error(`documents_load_failed:${documentsResult.error.message}`);const ids=(documentsResult.data??[]).map(row=>row.id);const[acceptances,events]=await Promise.all([ids.length?this.client.from("document_acceptances").select("id,document_id,signer_name,signer_document,accepted_at,ip_address,user_agent,document_hash,document_version,method,statement").in("document_id",ids):Promise.resolve({data:[],error:null}),ids.length?this.client.from("document_events").select("id,document_id,action,detail,actor,actor_type,occurred_at").in("document_id",ids).order("occurred_at",{ascending:false}):Promise.resolve({data:[],error:null})]);if(acceptances.error)throw new Error(`document_acceptances_load_failed:${acceptances.error.message}`);if(events.error)throw new Error(`document_events_load_failed:${events.error.message}`);return((documentsResult.data??[])as DocumentRow[]).map(row=>{const acceptance=((acceptances.data??[])as AcceptanceRow[]).find(value=>value.document_id===row.id);return{id:row.id,...(row.workflow_id?{workflowId:row.workflow_id}:{}),...(row.employee_id?{employeeId:row.employee_id}:{}),subjectName:row.subject_name,subjectDocument:row.subject_document,companyName:row.company_name,title:row.title,category:row.category,status:row.status,...(row.template_id?{templateId:row.template_id}:{}),...(row.template_name?{templateName:row.template_name}:{}),version:row.version,required:row.required,createdAt:row.created_at,updatedAt:row.updated_at,...(row.expires_at?{expiresAt:row.expires_at}:{}),...(row.validation_note?{validationNote:row.validation_note}:{}),preview:row.preview,...(acceptance?{acceptance:{id:acceptance.id,signerName:acceptance.signer_name,signerDocument:acceptance.signer_document,acceptedAt:acceptance.accepted_at,ipAddress:acceptance.ip_address,userAgent:acceptance.user_agent,documentHash:acceptance.document_hash,documentVersion:acceptance.document_version,method:acceptance.method,statement:acceptance.statement}}:{}),auditTrail:((events.data??[])as EventRow[]).filter(value=>value.document_id===row.id).map(value=>({id:value.id,action:value.action,detail:value.detail,actor:value.actor,type:value.actor_type,occurredAt:value.occurred_at}))}})}
 async overview():Promise<DocumentOverview>{const documents=await this.all();const result=await this.client.from("document_templates").select("id,name,category,version,active,variables,updated_at").order("name");if(result.error)throw new Error(`document_templates_load_failed:${result.error.message}`);return{summary:{total:documents.length,pendingValidation:documents.filter(x=>["received","under_review"].includes(x.status)).length,awaitingAcceptance:documents.filter(x=>x.status==="sent").length,accepted:documents.filter(x=>x.status==="accepted").length,expiringSoon:documents.filter(x=>x.expiresAt&&new Date(x.expiresAt)<new Date(Date.now()+30*86_400_000)).length},documents,templates:(result.data??[]).map(row=>({id:row.id,name:row.name,category:row.category,version:row.version,active:row.active,variables:row.variables,updatedAt:row.updated_at}))}}
 async find(id:string){return(await this.all(id))[0]}async create(input:CreateDocumentRequestInput){const{data,error}=await this.client.rpc("create_document_request",{document_payload:{...input,preview:genericPreview(input.title,input.subjectName)}});if(error)throw new Error(`document_create_failed:${error.message}`);return(await this.find(data as string))!}async validate(id:string,decision:"approve"|"reject",note:string){const{error}=await this.client.rpc("validate_document",{document_id_value:id,decision_value:decision,note_value:note});if(error){if(error.message.includes("document_not_found"))return;throw new Error(`document_validation_failed:${error.message}`)}return this.find(id)}async accept(id:string,signerName:string,signerDocument:string,ipAddress:string,userAgent:string){const{error}=await this.client.rpc("accept_document",{document_id_value:id,signer_name_value:signerName,signer_document_value:signerDocument,ip_address_value:ipAddress,user_agent_value:userAgent});if(error){if(error.message.includes("document_not_found"))return;throw new Error(`document_acceptance_failed:${error.message}`)}return this.find(id)}
}
