import type { CreateDocumentRequestInput, DocumentOverview, DocumentRecord } from "@fluxrh/contracts";

async function sha256(value: string) {
  const bytes = new TextEncoder().encode(value);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, "0")).join("");
}

const now = new Date();
const isoDays = (days: number) => new Date(now.getTime() + days * 86_400_000).toISOString();
const audit = (id: string, action: string, detail: string, actor: string, days = 0, type: "system" | "user" | "signer" = "system") => ({ id, action, detail, actor, occurredAt: isoDays(days), type });
const contractPreview = (name: string, company: string) => ({ heading: "CONTRATO INDIVIDUAL DE TRABALHO", subheading: `${company} · versão eletrônica`, paragraphs: [`Pelo presente instrumento, ${company}, doravante denominada EMPREGADORA, e ${name}, doravante denominado(a) EMPREGADO(A), firmam o presente contrato de trabalho.`, "As partes reconhecem a validade do aceite eletrônico e da respectiva trilha de evidências registrada pelo FluxRH."], clauses: [{ title: "1. Função e local de trabalho", body: "O empregado exercerá as atividades inerentes ao cargo informado no processo de admissão, observadas as necessidades operacionais e os limites legais." }, { title: "2. Jornada", body: "A jornada seguirá a escala e os intervalos cadastrados no prontuário, com registro de ponto e tratamento das ocorrências aplicáveis." }, { title: "3. Remuneração", body: "A remuneração mensal será aquela aprovada na solicitação de contratação, sujeita aos encargos e descontos legais." }, { title: "4. Vigência e aceite", body: "Este instrumento entra em vigor na data prevista de admissão e sua integridade é comprovada pelo hash registrado no comprovante de aceite." }] });
const genericPreview = (title: string, name: string) => ({ heading: title.toUpperCase(), subheading: `Documento de ${name}`, paragraphs: ["Documento recebido pelo portal do FluxRH para composição do prontuário digital.", "A validação registra a versão, o responsável, a data e as observações da conferência."], clauses: [] });

const documents: DocumentRecord[] = [
  { id: "doc_contract_camila", workflowId: "adm_camila", subjectName: "Camila Rocha", subjectDocument: "***.315.***-55", companyName: "Norte Facilities", title: "Contrato de trabalho", category: "contract", status: "sent", templateId: "tpl_contract_clt", templateName: "Contrato CLT padrão", version: 1, required: true, createdAt: isoDays(-5), updatedAt: isoDays(-1), preview: contractPreview("Camila Rocha", "Norte Facilities"), auditTrail: [audit("a1","Documento enviado","Contrato disponibilizado para aceite eletrônico.","FluxRH",-1),audit("a2","Documento gerado","Modelo preenchido com os dados validados da admissão.","FluxRH",-2)] },
  { id: "doc_contract_julia", workflowId: "adm_julia", subjectName: "Júlia Martins", subjectDocument: "***.184.***-20", companyName: "Grupo Flux", title: "Contrato de trabalho", category: "contract", status: "accepted", templateId: "tpl_contract_clt", templateName: "Contrato CLT padrão", version: 1, required: true, createdAt: isoDays(-14), updatedAt: isoDays(-9), preview: contractPreview("Júlia Martins", "Grupo Flux"), acceptance: { id: "accept_julia", signerName: "Júlia Martins", signerDocument: "***.184.***-20", acceptedAt: isoDays(-9), ipAddress: "177.42.18.90", userAgent: "Portal FluxRH", documentHash: "a14b3c0f5cc1e12bf42e68cdd99cc06f79efabda2800528883be935f8819c7c1", documentVersion: 1, method: "authenticated_acceptance", statement: "Li e aceito integralmente o documento apresentado." }, auditTrail: [audit("a3","Aceite registrado","Identidade, data, IP e hash vinculados ao documento.","Júlia Martins",-9,"signer"),audit("a4","Documento enviado","Contrato disponibilizado no portal.","FluxRH",-10),audit("a5","Documento gerado","Contrato gerado a partir do modelo v1.","FluxRH",-12)] },
  { id: "doc_address_marina", workflowId: "adm_marina", subjectName: "Marina Souza", subjectDocument: "***.482.***-09", companyName: "Grupo Flux", title: "Comprovante de residência", category: "personal", status: "under_review", version: 1, required: true, createdAt: isoDays(-4), updatedAt: isoDays(-1), preview: genericPreview("Comprovante de residência", "Marina Souza"), auditTrail: [audit("a6","Documento recebido","Arquivo enviado pelo portal de admissão.","Marina Souza",-1,"signer"),audit("a7","Documento solicitado","Solicitação automática enviada.","FluxRH",-4)] },
  { id: "doc_policy_carlos", employeeId: "emp_carlos", subjectName: "Carlos Mendes", subjectDocument: "***.193.***-42", companyName: "Grupo Flux", title: "Termo de ciência da política de ponto", category: "policy", status: "accepted", templateId: "tpl_policy_time", templateName: "Política de registro de ponto", version: 3, required: true, createdAt: isoDays(-40), updatedAt: isoDays(-35), preview: { heading: "TERMO DE CIÊNCIA", subheading: "Política de registro de ponto · versão 3", paragraphs: ["Declaro ter recebido, lido e compreendido a política de registro de jornada da empresa."], clauses: [{ title: "Responsabilidade", body: "As marcações devem refletir a jornada efetivamente realizada e toda divergência deve ser justificada pelos canais oficiais." }] }, acceptance: { id: "accept_carlos", signerName: "Carlos Mendes", signerDocument: "***.193.***-42", acceptedAt: isoDays(-35), ipAddress: "192.168.1.55", userAgent: "Portal FluxRH", documentHash: "6d6f3d17c37f3c7dfd921f55691bd1d20fe00b1e35bd8a1758521d9012414525", documentVersion: 3, method: "authenticated_acceptance", statement: "Li e aceito integralmente o documento apresentado." }, auditTrail: [audit("a8","Aceite registrado","Evidências eletrônicas anexadas.","Carlos Mendes",-35,"signer")] },
  { id: "doc_aso_beatriz", employeeId: "emp_beatriz", subjectName: "Beatriz Lima", subjectDocument: "***.702.***-18", companyName: "Grupo Flux", title: "ASO periódico", category: "occupational", status: "validated", version: 1, required: true, createdAt: isoDays(-50), updatedAt: isoDays(-49), expiresAt: isoDays(22), validationNote: "Documento legível e dentro da validade.", preview: genericPreview("ASO periódico", "Beatriz Lima"), auditTrail: [audit("a9","Documento validado","Conferência concluída pelo RH.","Marina Alves",-49,"user")] }
];

const templates = [
  { id: "tpl_contract_clt", name: "Contrato CLT padrão", category: "contract" as const, version: 1, active: true, variables: ["colaborador.nome","empresa.razao_social","cargo.nome","contrato.salario","contrato.admissao"], updatedAt: isoDays(-18) },
  { id: "tpl_policy_time", name: "Política de registro de ponto", category: "policy" as const, version: 3, active: true, variables: ["colaborador.nome","empresa.nome","politica.vigencia"], updatedAt: isoDays(-42) },
  { id: "tpl_vt", name: "Opção de vale-transporte", category: "benefit" as const, version: 2, active: true, variables: ["colaborador.nome","beneficio.valor","endereco.linhas"], updatedAt: isoDays(-25) }
];

export class InMemoryDocumentsRepository {
  async overview(): Promise<DocumentOverview> { return { summary: { total: documents.length, pendingValidation: documents.filter(x => ["received","under_review"].includes(x.status)).length, awaitingAcceptance: documents.filter(x => x.status === "sent").length, accepted: documents.filter(x => x.status === "accepted").length, expiringSoon: documents.filter(x => x.expiresAt && new Date(x.expiresAt) < new Date(Date.now()+30*86_400_000)).length }, documents: structuredClone(documents), templates: structuredClone(templates) }; }
  async find(id: string) { const value=documents.find(x=>x.id===id); return value?structuredClone(value):undefined; }
  async create(input: CreateDocumentRequestInput) { const value:DocumentRecord={ id:`doc_${crypto.randomUUID()}`, ...input, status:"requested", version:1, createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), preview:genericPreview(input.title,input.subjectName), auditTrail:[audit(crypto.randomUUID(),"Documento solicitado","Solicitação criada e disponibilizada no portal.","Marina Alves",0,"user")]}; documents.unshift(value); return structuredClone(value); }
  async validate(id:string,decision:"approve"|"reject",note:string){const value=documents.find(x=>x.id===id);if(!value)return undefined;value.status=decision==="approve"?"validated":"rejected";value.validationNote=note;value.updatedAt=new Date().toISOString();value.auditTrail.unshift(audit(crypto.randomUUID(),decision==="approve"?"Documento validado":"Documento rejeitado",note,"Marina Alves",0,"user"));return structuredClone(value)}
  async accept(id:string,signerName:string,signerDocument:string,ipAddress:string,userAgent:string){const value=documents.find(x=>x.id===id);if(!value)return undefined;const acceptedAt=new Date().toISOString();const hash=await sha256(JSON.stringify({id:value.id,version:value.version,preview:value.preview,signerName,signerDocument,acceptedAt}));value.status="accepted";value.updatedAt=acceptedAt;value.acceptance={id:`accept_${crypto.randomUUID()}`,signerName,signerDocument,acceptedAt,ipAddress,userAgent,documentHash:hash,documentVersion:value.version,method:"authenticated_acceptance",statement:"Li e aceito integralmente o documento apresentado."};value.auditTrail.unshift(audit(crypto.randomUUID(),"Aceite eletrônico registrado",`Comprovante gerado com hash ${hash.slice(0,12)}…`,signerName,0,"signer"));return structuredClone(value)}
}
