import type { Admission, CreateAdmissionInput, OperationalException, WorkflowAuditEvent, WorkflowOverview } from "@fluxrh/contracts";
import type { SupabaseClient } from "@supabase/supabase-js";
import { InMemoryWorkflowsRepository, makeAdmission, type WorkflowsRepository } from "./workflows.repository.js";
import { WorkflowEngine } from "./workflow.engine.js";

type InstanceRow = { id:string; status:Admission["status"]; current_step:Admission["currentStep"]; context:Omit<Admission,"id"|"tasks"> };
type TaskRow = { id:string; instance_id:string; step_key:Admission["currentStep"]; title:string; description:string; kind:Admission["tasks"][number]["kind"]; status:Admission["tasks"][number]["status"]; assignee_label:string; due_at:string; completed_at:string|null };
type AuditRow = { id:number; resource_id:string; action:string; actor_type:"user"|"system"|"integration"; occurred_at:string };

export class SupabaseWorkflowsRepository implements WorkflowsRepository {
  private engine=new WorkflowEngine();
  private factory=new InMemoryWorkflowsRepository();
  constructor(private client:SupabaseClient){}
  private async all():Promise<Admission[]>{
    const {data:instances,error}=await this.client.from("workflow_instances").select("id,status,current_step,context").eq("subject_type","candidate").order("started_at",{ascending:false});
    if(error)throw new Error(`admissions_load_failed:${error.message}`);
    const ids=(instances??[]).map(row=>row.id);
    const [result,auditResult]=await Promise.all([ids.length?this.client.from("workflow_tasks").select("id,instance_id,step_key,title,description,kind,status,assignee_label,due_at,completed_at").in("instance_id",ids).order("created_at"):Promise.resolve({data:[],error:null}),ids.length?this.client.from("audit_events").select("id,resource_id,action,actor_type,occurred_at").eq("resource_type","workflow_instance").in("resource_id",ids).order("occurred_at",{ascending:false}):Promise.resolve({data:[],error:null})]);
    if(result.error)throw new Error(`admission_tasks_load_failed:${result.error.message}`);if(auditResult.error)throw new Error(`admission_audit_load_failed:${auditResult.error.message}`);
    return (instances as InstanceRow[]??[]).map(row=>{const history=((auditResult.data??[]) as AuditRow[]).filter(event=>event.resource_id===row.id).map(event=>({id:String(event.id),title:event.action==="admission.created"?"Admissão iniciada":"Workflow atualizado",description:"Transição registrada na trilha de auditoria.",actor:event.actor_type==="user"?"Usuário autenticado":"FluxRH",occurredAt:event.occurred_at,type:event.actor_type==="user"?"user" as const:"system" as const}));return {...row.context,id:row.id,status:row.status,currentStep:row.current_step,history:history.length?history:row.context.history,tasks:(result.data as TaskRow[]??[]).filter(t=>t.instance_id===row.id).map(t=>({id:t.id,title:t.title,description:t.description,stepKey:t.step_key,kind:t.kind,status:t.status,assignee:t.assignee_label,dueAt:t.due_at,...(t.completed_at?{completedAt:t.completed_at}:{})}))}});
  }
  list(){return this.all();}
  async find(id:string){return (await this.all()).find(item=>item.id===id);}
  async overview():Promise<WorkflowOverview>{const instances=await this.all();const fallback=await this.factory.overview();const tasks=instances.flatMap(item=>item.tasks.filter(t=>t.status!=="completed").map(t=>({...t,workflowId:item.id,subject:item.candidateName})));return {...fallback,instances,tasks,summary:{running:instances.filter(x=>x.status==="running").length,pendingTasks:tasks.length,automatedToday:0,exceptions:instances.filter(x=>x.status==="exception").length}};}
  async create(input:CreateAdmissionInput){const draft=makeAdmission(crypto.randomUUID(),input.candidateName,"digital_admission",input.companyName,input.position);Object.assign(draft,input,{progress:0,startedAt:new Date().toISOString(),dueAt:new Date(Date.now()+10*86_400_000).toISOString()});const {data,error}=await this.client.rpc("save_admission_workflow",{admission_payload:{...draft,id:""}});if(error)throw new Error(`admission_create_failed:${error.message}`);return (await this.find(data as string))!;}
  async advance(id:string,note?:string){const current=await this.find(id);if(!current)return undefined;const updated=this.engine.advance(current,"Usuário autenticado",note);const {error}=await this.client.rpc("save_admission_workflow",{admission_payload:updated});if(error)throw new Error(`admission_transition_failed:${error.message}`);return this.find(id);}
  async exceptions():Promise<OperationalException[]>{const {data,error}=await this.client.from("operational_exceptions").select("id,source_type,source_id,title,description,priority,status,recommendation,due_at,resolved_at,resolution_note,created_at").eq("source_type","admission").order("created_at",{ascending:false});if(error)throw new Error(`workflow_exceptions_load_failed:${error.message}`);return (data??[]).map(row=>({id:row.id,title:row.title,description:row.description,area:"Admissão",priority:row.priority,status:row.status,dueAt:row.due_at??row.created_at,createdAt:row.created_at,sourceType:row.source_type,sourceId:row.source_id,recommendation:row.recommendation,resolvedAt:row.resolved_at,resolutionNote:row.resolution_note}));}
  async resolveException(id:string,note:string):Promise<OperationalException|undefined>{const {error}=await this.client.rpc("resolve_operational_exception",{exception_id:id,resolution_note_value:note});if(error){if(error.message.includes("exception_not_found"))return undefined;throw new Error(`workflow_exception_resolve_failed:${error.message}`);}return (await this.exceptions()).find(item=>item.id===id);}
  async audit(workflowId?:string):Promise<WorkflowAuditEvent[]>{let query=this.client.from("audit_events").select("id,actor_type,actor_id,action,resource_type,resource_id,before_data,after_data,occurred_at").eq("resource_type","workflow_instance").order("occurred_at",{ascending:false});if(workflowId)query=query.eq("resource_id",workflowId);const {data,error}=await query.limit(100);if(error)throw new Error(`workflow_audit_load_failed:${error.message}`);return(data??[]).map(row=>({id:String(row.id),actorType:row.actor_type,actorId:row.actor_id,action:row.action,resourceType:row.resource_type,resourceId:row.resource_id,beforeData:row.before_data,afterData:row.after_data,occurredAt:row.occurred_at}));}
  async createException(id:string,title:string,description:string,priority:OperationalException["priority"]):Promise<OperationalException|undefined>{const {data,error}=await this.client.rpc("create_admission_exception",{workflow_id:id,exception_title:title,exception_description:description,exception_priority_value:priority});if(error){if(error.message.includes("admission_not_found"))return undefined;throw new Error(`workflow_exception_create_failed:${error.message}`);}return (await this.exceptions()).find(item=>item.id===data);}
}

