import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Check, CheckCircle2, Clock3, FileCheck2, FileSignature, FileText, Fingerprint, Hash, MonitorSmartphone, Printer, ShieldCheck, XCircle } from "lucide-react";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Modal } from "@/components/ui/Modal";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { acceptDocument, getDocument, validateDocument } from "@/lib/api";
import { categoryLabels, statusLabels, statusTones } from "./document-ui";

export function DocumentDetailPage(){
  const {id=""}=useParams();const client=useQueryClient();const {data:doc,isLoading}=useQuery({queryKey:["document",id],queryFn:()=>getDocument(id)});const [validationOpen,setValidationOpen]=useState(false);const [acceptOpen,setAcceptOpen]=useState(false);const [decision,setDecision]=useState<"approve"|"reject">("approve");const [note,setNote]=useState("Documento conferido e informações consistentes.");
  const update=(value:NonNullable<typeof doc>)=>{client.setQueryData(["document",id],value);client.invalidateQueries({queryKey:["documents"]})};
  const validation=useMutation({mutationFn:()=>validateDocument(id,decision,note),onSuccess:value=>{update(value);setValidationOpen(false)}});const acceptance=useMutation({mutationFn:()=>acceptDocument(id,doc?.subjectName??"",doc?.subjectDocument??""),onSuccess:value=>{update(value);setAcceptOpen(false)}});
  if(isLoading||!doc)return <div className="page"><div className="page-skeleton"/></div>;
  const canValidate=["received","under_review"].includes(doc.status);const canAccept=["generated","sent"].includes(doc.status);
  return <div className="page document-detail"><Link className="back-link" to="/documentos"><ArrowLeft/> Voltar para documentos</Link><section className="document-detail-head"><div><span className={`document-type-icon ${doc.category}`}><FileText/></span><div><span className="eyebrow">{categoryLabels[doc.category]} · versão {doc.version}</span><h1>{doc.title}</h1><p>{doc.subjectName} · {doc.companyName}</p></div></div><div className="document-actions"><StatusBadge tone={statusTones[doc.status]}>{statusLabels[doc.status]}</StatusBadge><button className="secondary-button" onClick={()=>window.print()}><Printer/> Imprimir</button>{canValidate&&<button className="primary-button" onClick={()=>setValidationOpen(true)}><FileCheck2/> Validar</button>}{canAccept&&<button className="primary-button" onClick={()=>setAcceptOpen(true)}><FileSignature/> Registrar aceite</button>}</div></section>
    <div className="document-detail-grid"><main className="document-paper"><header><span className="paper-brand">Flux<strong>RH</strong></span><small>Documento eletrônico · ID {doc.id}</small></header><h2>{doc.preview.heading}</h2><h3>{doc.preview.subheading}</h3>{doc.preview.paragraphs.map((paragraph,index)=><p key={index}>{paragraph}</p>)}{doc.preview.clauses.map((clause,index)=><section key={index}><h4>{clause.title}</h4><p>{clause.body}</p></section>)}<footer><span>Versão {doc.version}</span><span>Gerado em {new Date(doc.createdAt).toLocaleString("pt-BR")}</span></footer>{doc.acceptance&&<div className="paper-stamp"><ShieldCheck/><span><strong>ACEITO ELETRONICAMENTE</strong><small>{new Date(doc.acceptance.acceptedAt).toLocaleString("pt-BR")}</small></span></div>}</main>
      <aside className="document-side"><section className="panel document-metadata"><h2>Informações</h2><Meta label="Titular" value={doc.subjectName}/><Meta label="Identificador" value={doc.subjectDocument}/><Meta label="Modelo" value={doc.templateName??"Documento recebido"}/><Meta label="Versão" value={`v${doc.version}`}/><Meta label="Criado em" value={new Date(doc.createdAt).toLocaleDateString("pt-BR")}/>{doc.expiresAt&&<Meta label="Validade" value={new Date(doc.expiresAt).toLocaleDateString("pt-BR")}/>}</section>{doc.acceptance&&<AcceptanceReceipt doc={doc}/>}<section className="panel document-audit"><h2>Trilha de auditoria</h2>{doc.auditTrail.map(event=><div key={event.id}><i className={event.type}/><span><strong>{event.action}</strong><p>{event.detail}</p><small>{event.actor} · {new Date(event.occurredAt).toLocaleString("pt-BR")}</small></span></div>)}</section></aside>
    </div>
    <Modal open={validationOpen} onClose={()=>setValidationOpen(false)} title="Validar documento" description="A decisão e a justificativa serão registradas na trilha de auditoria."><div className="validation-modal"><div className="decision-toggle"><button className={decision==="approve"?"approve active":"approve"} onClick={()=>{setDecision("approve");setNote("Documento conferido e informações consistentes.")}}><CheckCircle2/> Aprovar</button><button className={decision==="reject"?"reject active":"reject"} onClick={()=>{setDecision("reject");setNote("Documento ilegível ou com informações inconsistentes.")}}><XCircle/> Rejeitar</button></div><label>Justificativa<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><footer className="form-actions"><button className="secondary-button" onClick={()=>setValidationOpen(false)}>Cancelar</button><button className="primary-button" disabled={note.length<3||validation.isPending} onClick={()=>validation.mutate()}>{validation.isPending?"Registrando...":"Confirmar validação"}</button></footer></div></Modal>
    <Modal open={acceptOpen} onClose={()=>setAcceptOpen(false)} title="Aceite eletrônico" description="Confira o documento e confirme a manifestação de vontade."><div className="acceptance-modal"><div className="acceptance-identity"><Fingerprint/><span><small>Signatário autenticado</small><strong>{doc.subjectName}</strong><p>{doc.subjectDocument}</p></span></div><div className="acceptance-statement"><Check/><p>Declaro que li o documento apresentado e aceito integralmente seus termos. Estou ciente de que serão registradas evidências eletrônicas deste aceite.</p></div><div className="evidence-preview"><span><Hash/> Hash SHA-256</span><span><Clock3/> Data e hora</span><span><MonitorSmartphone/> IP e dispositivo</span></div><footer className="form-actions"><button className="secondary-button" onClick={()=>setAcceptOpen(false)}>Cancelar</button><button className="primary-button" disabled={acceptance.isPending} onClick={()=>acceptance.mutate()}>{acceptance.isPending?"Gerando evidências...":"Li e aceito o documento"}</button></footer></div></Modal>
  </div>;
}
function Meta({label,value}:{label:string;value:string}){return <div><small>{label}</small><strong>{value}</strong></div>}
function AcceptanceReceipt({doc}:{doc:NonNullable<Awaited<ReturnType<typeof getDocument>>>}){const evidence=doc.acceptance!;return <section className="panel acceptance-receipt"><header><ShieldCheck/><div><small>COMPROVANTE</small><h2>Aceite eletrônico</h2></div></header><Meta label="Signatário" value={evidence.signerName}/><Meta label="Data e hora" value={new Date(evidence.acceptedAt).toLocaleString("pt-BR")}/><Meta label="Endereço IP" value={evidence.ipAddress}/><div className="hash-box"><small>SHA-256 · versão {evidence.documentVersion}</small><code>{evidence.documentHash}</code></div></section>}
