create table public.time_schedules(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,pattern text not null,start_time time not null,end_time time not null,break_minutes integer not null check(break_minutes>=0),weekly_hours numeric(5,2) not null,night_shift boolean not null default false,color text not null default '#155eef',active boolean not null default true,created_at timestamptz not null default now(),unique(organization_id,name));
create table public.employee_schedules(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,employee_id uuid not null references public.employees(id) on delete cascade,schedule_id uuid not null references public.time_schedules(id) on delete restrict,valid_from date not null,valid_to date,created_at timestamptz not null default now(),unique(employee_id,valid_from));
create table public.time_stations(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,token text not null unique,rotates_at timestamptz not null,active boolean not null default true,created_at timestamptz not null default now());
create table public.time_punches(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,employee_id uuid not null references public.employees(id) on delete restrict,type text not null check(type in('clock_in','break_start','break_end','clock_out')),recorded_at timestamptz not null default now(),source text not null check(source in('qr_code','manual','offline_sync')),station_id uuid references public.time_stations(id) on delete restrict,location_name text not null,device_id text not null,latitude numeric,longitude numeric,created_by uuid references auth.users(id),created_at timestamptz not null default now());
create table public.time_exceptions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,employee_id uuid not null references public.employees(id) on delete cascade,date date not null,type text not null,title text not null,description text not null,severity text not null check(severity in('critical','high','medium','low')),status text not null default 'open' check(status in('open','in_review','resolved')),minutes integer,resolution_note text,resolved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.timesheet_approvals(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,employee_id uuid not null references public.employees(id) on delete cascade,competence date not null,status text not null default 'approved' check(status in('open','review','approved')),approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(employee_id,competence));
create index time_punches_employee_recorded_idx on public.time_punches(employee_id,recorded_at desc);create index time_exceptions_employee_date_idx on public.time_exceptions(employee_id,date desc);create index timesheet_approvals_competence_idx on public.timesheet_approvals(organization_id,competence);
alter table public.time_schedules enable row level security;alter table public.employee_schedules enable row level security;alter table public.time_stations enable row level security;alter table public.time_punches enable row level security;alter table public.time_exceptions enable row level security;alter table public.timesheet_approvals enable row level security;
revoke all on public.time_schedules,public.employee_schedules,public.time_stations,public.time_punches,public.time_exceptions,public.timesheet_approvals from anon,authenticated;grant select on public.time_schedules,public.employee_schedules,public.time_stations,public.time_punches,public.time_exceptions,public.timesheet_approvals to authenticated;
create policy time_schedules_select on public.time_schedules for select to authenticated using((select private.is_active_member(organization_id)));create policy employee_schedules_select on public.employee_schedules for select to authenticated using((select private.is_active_member(organization_id)));create policy time_stations_select on public.time_stations for select to authenticated using((select private.is_active_member(organization_id)));
create policy time_punches_select on public.time_punches for select to authenticated using((select private.has_organization_role(organization_id,array['owner','admin','hr','manager','auditor']::public.organization_role[])) or exists(select 1 from public.employees e where e.id=employee_id and e.user_id=(select auth.uid())));
create policy time_exceptions_select on public.time_exceptions for select to authenticated using((select private.has_organization_role(organization_id,array['owner','admin','hr','manager','auditor']::public.organization_role[])) or exists(select 1 from public.employees e where e.id=employee_id and e.user_id=(select auth.uid())));
create policy timesheet_approvals_select on public.timesheet_approvals for select to authenticated using((select private.has_organization_role(organization_id,array['owner','admin','hr','manager','auditor']::public.organization_role[])) or exists(select 1 from public.employees e where e.id=employee_id and e.user_id=(select auth.uid())));

insert into public.time_schedules(organization_id,name,pattern,start_time,end_time,break_minutes,weekly_hours,night_shift,color) select id,'Administrativo 5×2','5x2','08:00','17:48',60,44,false,'#155eef' from public.organizations on conflict do nothing;
insert into public.time_stations(organization_id,name,token,rotates_at) select id,'Recepção · Matriz','FLUXRH-'||upper(substr(replace(id::text,'-',''),1,12)),now()+interval '10 years' from public.organizations;
create or replace function private.bootstrap_time_organization()returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.time_schedules(organization_id,name,pattern,start_time,end_time,break_minutes,weekly_hours,night_shift,color)values(new.id,'Administrativo 5×2','5x2','08:00','17:48',60,44,false,'#155eef');insert into public.time_stations(organization_id,name,token,rotates_at)values(new.id,'Recepção · Matriz','FLUXRH-'||upper(substr(replace(new.id::text,'-',''),1,12)),now()+interval '10 years');return new;end;$$;create trigger organization_time_bootstrap after insert on public.organizations for each row execute function private.bootstrap_time_organization();

create or replace function public.register_time_punch(employee_id_value uuid,punch_type_value text,station_token_value text,device_id_value text,location_name_value text)returns uuid language plpgsql security definer set search_path='' as $$
declare organization_id_value uuid;station_id_value uuid;punch_id_value uuid;last_type text;
begin select organization_id into organization_id_value from public.employees where id=employee_id_value;if organization_id_value is null then raise exception 'employee_not_found' using errcode='P0002';end if;if not(private.has_organization_role(organization_id_value,array['owner','admin','hr','manager']::public.organization_role[]) or exists(select 1 from public.employees where id=employee_id_value and user_id=(select auth.uid())))then raise exception 'punch_forbidden' using errcode='42501';end if;if punch_type_value not in('clock_in','break_start','break_end','clock_out')then raise exception 'invalid_punch_type' using errcode='22023';end if;select id into station_id_value from public.time_stations where organization_id=organization_id_value and token=station_token_value and active=true and rotates_at>now();if station_id_value is null then raise exception 'invalid_token' using errcode='22023';end if;select type into last_type from public.time_punches where employee_id=employee_id_value and recorded_at::date=current_date order by recorded_at desc limit 1;if last_type=punch_type_value then raise exception 'duplicate_punch_type' using errcode='22023';end if;insert into public.time_punches(organization_id,employee_id,type,source,station_id,location_name,device_id,created_by)values(organization_id_value,employee_id_value,punch_type_value,'qr_code',station_id_value,location_name_value,device_id_value,(select auth.uid()))returning id into punch_id_value;insert into public.domain_events(organization_id,aggregate_type,aggregate_id,event_type,payload)values(organization_id_value,'time_punch',punch_id_value,'time.punch_registered',jsonb_build_object('employeeId',employee_id_value,'type',punch_type_value));return punch_id_value;end;$$;
create or replace function public.resolve_time_exception(exception_id_value uuid,resolution_note_value text)returns void language plpgsql security definer set search_path='' as $$declare organization_id_value uuid;before_value jsonb;begin select organization_id,to_jsonb(e) into organization_id_value,before_value from public.time_exceptions e where id=exception_id_value for update;if organization_id_value is null then raise exception 'exception_not_found' using errcode='P0002';end if;if not private.has_organization_role(organization_id_value,array['owner','admin','hr','manager']::public.organization_role[])then raise exception 'exception_resolve_forbidden' using errcode='42501';end if;if length(trim(coalesce(resolution_note_value,'')))<3 then raise exception 'invalid_resolution_note' using errcode='22023';end if;update public.time_exceptions set status='resolved',resolution_note=trim(resolution_note_value),resolved_at=now(),updated_at=now()where id=exception_id_value;insert into public.audit_events(organization_id,actor_type,actor_id,action,resource_type,resource_id,before_data,after_data)values(organization_id_value,'user',(select auth.uid()),'time.exception_resolved','time_exception',exception_id_value::text,before_value,(select to_jsonb(e)from public.time_exceptions e where id=exception_id_value));end;$$;
create or replace function public.approve_employee_timesheet(employee_id_value uuid,competence_value date)returns void language plpgsql security definer set search_path='' as $$declare organization_id_value uuid;begin select organization_id into organization_id_value from public.employees where id=employee_id_value;if organization_id_value is null then raise exception 'employee_not_found' using errcode='P0002';end if;if not private.has_organization_role(organization_id_value,array['owner','admin','hr','manager']::public.organization_role[])then raise exception 'timesheet_approve_forbidden' using errcode='42501';end if;if exists(select 1 from public.time_exceptions where employee_id=employee_id_value and date_trunc('month',date)=date_trunc('month',competence_value) and status<>'resolved')then raise exception 'timesheet_has_open_exceptions' using errcode='22023';end if;insert into public.timesheet_approvals(organization_id,employee_id,competence,status,approved_by,approved_at)values(organization_id_value,employee_id_value,date_trunc('month',competence_value)::date,'approved',(select auth.uid()),now())on conflict(employee_id,competence)do update set status='approved',approved_by=(select auth.uid()),approved_at=now(),updated_at=now();insert into public.audit_events(organization_id,actor_type,actor_id,action,resource_type,resource_id,after_data)values(organization_id_value,'user',(select auth.uid()),'timesheet.approved','employee',employee_id_value::text,jsonb_build_object('competence',date_trunc('month',competence_value)::date));end;$$;
revoke all on function public.register_time_punch(uuid,text,text,text,text),public.resolve_time_exception(uuid,text),public.approve_employee_timesheet(uuid,date)from public,anon;grant execute on function public.register_time_punch(uuid,text,text,text,text),public.resolve_time_exception(uuid,text),public.approve_employee_timesheet(uuid,date)to authenticated;
