create table public.document_templates(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,category text not null,version integer not null check(version>0),active boolean not null default true,
  variables jsonb not null default '[]'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,name,version)
);
create table public.documents(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,
  workflow_id uuid references public.workflow_instances(id) on delete set null,employee_id uuid references public.employees(id) on delete set null,
  subject_name text not null,subject_document text not null,company_name text not null,title text not null,category text not null,
  status text not null,template_id uuid references public.document_templates(id) on delete set null,template_name text,version integer not null default 1 check(version>0),
  required boolean not null default true,preview jsonb not null,expires_at timestamptz,validation_note text,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  check(category in('personal','contract','occupational','payroll','benefit','policy')),
  check(status in('requested','received','under_review','validated','rejected','generated','sent','accepted','expired'))
);
create table public.document_acceptances(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,
  document_id uuid not null unique references public.documents(id) on delete restrict,signer_name text not null,signer_document text not null,
  accepted_at timestamptz not null,ip_address text not null,user_agent text not null,document_hash text not null check(length(document_hash)=64),
  document_version integer not null,method text not null default 'authenticated_acceptance',statement text not null,created_at timestamptz not null default now()
);
create table public.document_events(
  id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete restrict,
  document_id uuid not null references public.documents(id) on delete restrict,action text not null,detail text not null,actor text not null,
  actor_type text not null check(actor_type in('system','user','signer')),occurred_at timestamptz not null default now()
);
create index documents_organization_idx on public.documents(organization_id,updated_at desc);create index document_events_document_idx on public.document_events(document_id,occurred_at desc);
alter table public.document_templates enable row level security;alter table public.documents enable row level security;alter table public.document_acceptances enable row level security;alter table public.document_events enable row level security;
revoke all on public.document_templates,public.documents,public.document_acceptances,public.document_events from anon,authenticated;
grant select on public.document_templates,public.documents,public.document_acceptances,public.document_events to authenticated;
create policy document_templates_select on public.document_templates for select to authenticated using((select private.is_active_member(organization_id)));
create policy documents_select on public.documents for select to authenticated using((select private.has_organization_role(organization_id,array['owner','admin','hr','manager','auditor']::public.organization_role[])) or exists(select 1 from public.employees e where e.id=employee_id and e.user_id=(select auth.uid())));
create policy document_acceptances_select on public.document_acceptances for select to authenticated using((select private.has_organization_role(organization_id,array['owner','admin','hr','auditor']::public.organization_role[])) or exists(select 1 from public.documents d join public.employees e on e.id=d.employee_id where d.id=document_id and e.user_id=(select auth.uid())));
create policy document_events_select on public.document_events for select to authenticated using((select private.has_organization_role(organization_id,array['owner','admin','hr','auditor']::public.organization_role[])) or exists(select 1 from public.documents d join public.employees e on e.id=d.employee_id where d.id=document_id and e.user_id=(select auth.uid())));

create or replace function public.create_document_request(document_payload jsonb) returns uuid language plpgsql security definer set search_path='' as $$
declare organization_id_value uuid;document_id_value uuid;
begin
  select organization_id into organization_id_value from public.organization_members where user_id=(select auth.uid()) and status='active' order by created_at limit 1;
  if organization_id_value is null or not private.has_organization_role(organization_id_value,array['owner','admin','hr']::public.organization_role[]) then raise exception 'document_create_forbidden' using errcode='42501';end if;
  if coalesce(document_payload->>'subjectName','')='' or coalesce(document_payload->>'title','')='' or document_payload->>'category' not in('personal','contract','occupational','payroll','benefit','policy') or jsonb_typeof(document_payload->'preview')<>'object' then raise exception 'invalid_document_payload' using errcode='22023';end if;
  insert into public.documents(organization_id,workflow_id,employee_id,subject_name,subject_document,company_name,title,category,status,version,required,preview)
  values(organization_id_value,nullif(document_payload->>'workflowId','')::uuid,nullif(document_payload->>'employeeId','')::uuid,document_payload->>'subjectName',document_payload->>'subjectDocument',document_payload->>'companyName',document_payload->>'title',document_payload->>'category','requested',1,coalesce((document_payload->>'required')::boolean,true),document_payload->'preview') returning id into document_id_value;
  insert into public.document_events(organization_id,document_id,action,detail,actor,actor_type) values(organization_id_value,document_id_value,'Documento solicitado','Solicitação criada e disponibilizada no portal.','Usuário autenticado','user');
  insert into public.audit_events(organization_id,actor_type,actor_id,action,resource_type,resource_id,after_data) values(organization_id_value,'user',(select auth.uid()),'document.requested','document',document_id_value::text,document_payload-'preview');return document_id_value;
end;$$;
create or replace function public.validate_document(document_id_value uuid,decision_value text,note_value text) returns void language plpgsql security definer set search_path='' as $$
declare organization_id_value uuid;before_value jsonb;status_value text;
begin select organization_id,to_jsonb(d) into organization_id_value,before_value from public.documents d where id=document_id_value for update;if organization_id_value is null then raise exception 'document_not_found' using errcode='P0002';end if;if not private.has_organization_role(organization_id_value,array['owner','admin','hr']::public.organization_role[]) then raise exception 'document_validate_forbidden' using errcode='42501';end if;if decision_value not in('approve','reject') or length(trim(coalesce(note_value,'')))<3 then raise exception 'invalid_validation' using errcode='22023';end if;status_value:=case when decision_value='approve' then 'validated' else 'rejected' end;update public.documents set status=status_value,validation_note=trim(note_value),updated_at=now() where id=document_id_value;insert into public.document_events(organization_id,document_id,action,detail,actor,actor_type) values(organization_id_value,document_id_value,case when decision_value='approve' then 'Documento validado' else 'Documento rejeitado' end,trim(note_value),'Usuário autenticado','user');insert into public.audit_events(organization_id,actor_type,actor_id,action,resource_type,resource_id,before_data,after_data) values(organization_id_value,'user',(select auth.uid()),'document.'||status_value,'document',document_id_value::text,before_value,(select to_jsonb(d) from public.documents d where id=document_id_value));end;$$;
create or replace function public.accept_document(document_id_value uuid,signer_name_value text,signer_document_value text,ip_address_value text,user_agent_value text) returns void language plpgsql security definer set search_path='' as $$
declare organization_id_value uuid;version_value integer;preview_value jsonb;accepted_at_value timestamptz:=now();hash_value text;
begin select organization_id,version,preview into organization_id_value,version_value,preview_value from public.documents where id=document_id_value for update;if organization_id_value is null then raise exception 'document_not_found' using errcode='P0002';end if;if not (private.has_organization_role(organization_id_value,array['owner','admin','hr']::public.organization_role[]) or exists(select 1 from public.documents d join public.employees e on e.id=d.employee_id where d.id=document_id_value and e.user_id=(select auth.uid()))) then raise exception 'document_accept_forbidden' using errcode='42501';end if;if exists(select 1 from public.document_acceptances where document_id=document_id_value) then raise exception 'document_already_accepted' using errcode='23505';end if;hash_value:=encode(extensions.digest(convert_to(jsonb_build_object('id',document_id_value,'version',version_value,'preview',preview_value,'signerName',signer_name_value,'signerDocument',signer_document_value,'acceptedAt',accepted_at_value)::text,'UTF8'),'sha256'),'hex');insert into public.document_acceptances(organization_id,document_id,signer_name,signer_document,accepted_at,ip_address,user_agent,document_hash,document_version,statement) values(organization_id_value,document_id_value,signer_name_value,signer_document_value,accepted_at_value,ip_address_value,user_agent_value,hash_value,version_value,'Li e aceito integralmente o documento apresentado.');update public.documents set status='accepted',updated_at=accepted_at_value where id=document_id_value;insert into public.document_events(organization_id,document_id,action,detail,actor,actor_type,occurred_at) values(organization_id_value,document_id_value,'Aceite eletrônico registrado','Comprovante de integridade e autoria gerado.',signer_name_value,'signer',accepted_at_value);insert into public.audit_events(organization_id,actor_type,actor_id,action,resource_type,resource_id,after_data) values(organization_id_value,'user',(select auth.uid()),'document.accepted','document',document_id_value::text,jsonb_build_object('hash',hash_value,'version',version_value,'acceptedAt',accepted_at_value));end;$$;
revoke all on function public.create_document_request(jsonb),public.validate_document(uuid,text,text),public.accept_document(uuid,text,text,text,text) from public,anon;
grant execute on function public.create_document_request(jsonb),public.validate_document(uuid,text,text),public.accept_document(uuid,text,text,text,text) to authenticated;
