import { ArrowRight, CheckCircle2, Plus, Sparkles, TrendingUp } from 'lucide-react';
import { areaFixtures, type AreaKey } from './area-fixtures';

const toneClasses = { normal: 'bg-emerald-50 text-emerald-800 ring-emerald-200', attention: 'bg-amber-50 text-amber-900 ring-amber-200', critical: 'bg-rose-50 text-rose-800 ring-rose-200', default: 'bg-blue-50 text-blue-800 ring-blue-200' };

export const ProductAreaPage = ({ area }: { area: AreaKey }) => {
  const fixture = areaFixtures[area];
  return (
    <div className="mx-auto max-w-[1440px] space-y-6">
      <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-700">{fixture.eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">{fixture.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 sm:text-base">{fixture.description}</p></div><button type="button" className="inline-flex items-center justify-center gap-2 self-start rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:ring-offset-2"><Plus className="h-4 w-4" aria-hidden="true" /> {fixture.primaryAction}</button></header>
      <section className="grid gap-3 md:grid-cols-3" aria-label="Indicadores principais">{fixture.metrics.map((metric) => <article key={metric.label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-medium text-slate-500">{metric.label}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{metric.value}</p><p className={`mt-3 text-xs ${metric.tone === 'positive' ? 'text-emerald-700' : metric.tone === 'attention' ? 'text-amber-700' : 'text-slate-500'}`}>{metric.detail}</p></article>)}</section>
      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]">
        <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Visão operacional</p><h2 className="mt-1 text-lg font-semibold">{fixture.queueTitle}</h2></div><button type="button" className="text-sm font-semibold text-blue-700 hover:text-blue-900">Ver todos</button></div><div className="divide-y divide-slate-100">{fixture.queue.map((item) => { const tone = item.tone ?? 'default'; return <button key={item.title} type="button" className="flex w-full flex-col gap-3 px-5 py-4 text-left transition hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-blue-500 sm:flex-row sm:items-center"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${tone === 'critical' ? 'bg-rose-500' : tone === 'attention' ? 'bg-amber-500' : tone === 'normal' ? 'bg-emerald-500' : 'bg-blue-500'}`} aria-hidden="true" /><span className="min-w-0 flex-1"><strong className="block text-sm text-slate-950">{item.title}</strong><span className="mt-1 block text-sm text-slate-600">{item.detail}</span><span className="mt-1.5 block text-xs text-slate-400">{item.meta}</span></span><span className={`inline-flex self-start rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset sm:self-center ${toneClasses[tone]}`}>{item.status}</span><ArrowRight className="hidden h-4 w-4 text-slate-300 sm:block" aria-hidden="true" /></button>; })}</div></section>
        <aside className="space-y-4"><section className="overflow-hidden rounded-2xl bg-slate-950 p-5 text-white shadow-lg"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-blue-300"><Sparkles className="h-4 w-4" /> Leitura do FluxPay AI</div><p className="mt-4 text-sm leading-6 text-slate-200">{fixture.insight}</p><button type="button" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-white">Explorar análise <ArrowRight className="h-4 w-4" /></button></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><CheckCircle2 className="h-5 w-5 text-emerald-600" /><h2 className="font-semibold">Operação saudável</h2></div><p className="mt-3 text-sm leading-6 text-slate-600">Monitores e regras estão ativos. Eventos relevantes serão trazidos para decisão.</p><div className="mt-4 flex items-center gap-2 text-xs font-medium text-emerald-700"><TrendingUp className="h-4 w-4" /> Atualizado há 2 minutos</div></section></aside>
      </div>
    </div>
  );
};
