import { BookOpen, ChevronRight, CircleHelp, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router-dom";

type ManualSection = {
  id: string;
  title: string;
  path: string;
  purpose: string;
  steps: string[];
  notes?: string[];
};

const sections: ManualSection[] = [
  { id:"overview", title:"Visão geral", path:"/", purpose:"Acompanhar indicadores, pendências e prioridades da operação de RH em uma única tela.", steps:["Confira os cartões de métricas para entender o volume e o estado da operação.","Use a lista de prioridades para identificar itens que precisam de ação humana.","Abra um cartão ou atalho para acessar o módulo relacionado.","Revise alertas e exceções antes de iniciar rotinas de fechamento."], notes:["Indicadores são resumos; confirme detalhes no módulo de origem antes de decidir."] },
  { id:"exceptions", title:"Central de exceções", path:"/excecoes", purpose:"Tratar situações que interromperam uma automação ou exigem decisão humana.", steps:["Filtre as exceções por prioridade, módulo ou situação.","Abra a ocorrência e leia o contexto, a evidência e o impacto.","Faça a correção solicitada no módulo de origem, quando necessário.","Registre uma justificativa clara e use a ação de resolução.","Confirme no histórico que o fluxo foi retomado."], notes:["Não resolva uma exceção apenas para removê-la da fila; a justificativa compõe a auditoria."] },
  { id:"people", title:"Pessoas e prontuários", path:"/pessoas", purpose:"Consultar colaboradores, vínculos, documentos e histórico individual.", steps:["Use a busca por nome ou matrícula e filtre pelo status.","Selecione um colaborador para abrir o prontuário completo.","Navegue pelas abas de dados pessoais, vínculo, documentos, dependentes e linha do tempo.","Para cadastrar alguém, selecione “Novo colaborador”, preencha os dados e confirme.","Revise empresa, unidade, departamento e centro de custo antes de salvar."], notes:["Cadastros fictícios são identificados por matrícula ou documento iniciado com FICT e e-mail example.invalid."] },
  { id:"portal", title:"Meu portal", path:"/portal", purpose:"Centralizar solicitações, documentos e tarefas do colaborador ou gestor.", steps:["Confira solicitações recentes e seus status.","Abra uma solicitação para consultar prazos e histórico.","Acesse documentos disponibilizados para o perfil autenticado.","Gestores podem revisar e decidir itens encaminhados à sua equipe."] },
  { id:"admissions", title:"Admissões", path:"/admissoes", purpose:"Conduzir a admissão desde o cadastro inicial até o onboarding.", steps:["Selecione “Nova admissão” e informe candidato, cargo, salário, gestor e data prevista.","Confira o checklist e os documentos solicitados.","Avance cada etapa somente após validar os requisitos apresentados.","Trate exceções cadastrais ou documentais na própria admissão.","Ao concluir contrato e aceite, confirme o checklist de onboarding."], notes:["O avanço de etapa gera histórico e pode criar tarefas automáticas."] },
  { id:"companies", title:"Empresas e unidades", path:"/empresas", purpose:"Manter a estrutura que organiza vínculos, custos, regras e permissões.", steps:["Consulte o resumo de empresas, estabelecimentos, departamentos e centros de custo.","Use a aba Empresas para conferir razão social, documento e sede.","Use a aba Hierarquia para entender as relações entre unidades.","Selecione “Nova empresa” para cadastrar uma entidade e revise os dados antes de confirmar."], notes:["Colaboradores só aparecem corretamente quando possuem vínculo com todas as unidades exigidas."] },
  { id:"time", title:"Jornada e ponto", path:"/jornada", purpose:"Registrar marcações, apurar jornadas e fechar competências.", steps:["Confira escalas e competência selecionada.","Use a leitura de QR Code para registrar marcações autorizadas.","Revise atrasos, ausências e divergências na área de exceções.","Resolva pendências com justificativa e evidência.","Aprove o espelho somente quando não houver exceções abertas."], notes:["A aprovação do ponto é bloqueada enquanto existirem divergências pendentes."] },
  { id:"absences", title:"Férias e ausências", path:"/ferias", purpose:"Gerenciar férias, afastamentos, atestados e períodos concessivos.", steps:["Consulte saldos, períodos e solicitações abertas.","Abra uma solicitação para revisar datas, duração e impacto operacional.","Valide documentos quando o tipo de ausência exigir comprovação.","Aprove, rejeite ou solicite ajuste registrando a decisão.","Acompanhe o calendário para evitar conflitos de equipe."], notes:["Confirme regras trabalhistas aplicáveis antes de aprovar períodos oficiais."] },
  { id:"benefits", title:"Benefícios", path:"/beneficios", purpose:"Administrar planos, adesões, dependentes e movimentos para a folha.", steps:["Consulte planos disponíveis, custos e elegibilidade.","Cadastre uma adesão selecionando colaborador, plano, início e dependentes.","Revise movimentos pendentes e sua documentação.","Aprove ou rejeite o movimento com uma nota objetiva.","Confira se o lançamento foi encaminhado para a prévia da folha."] },
  { id:"calculations", title:"13º e cálculos especiais", path:"/calculos", purpose:"Calcular férias, décimo terceiro e eventos fora da folha recorrente.", steps:["Selecione a competência e o tipo de cálculo.","Confira bases, avos, proventos, descontos e valor líquido.","Resolva divergências antes da aprovação.","Aprove o cálculo e confirme a geração do recibo.","Use o histórico para consultar versões e decisões anteriores."] },
  { id:"payroll", title:"Folha", path:"/folha", purpose:"Executar pré-fechamento, conferência e aprovação da folha.", steps:["Abra a competência e confira totais de proventos, descontos e líquido.","Analise colaboradores com alertas ou diferenças.","Abra a memória de cálculo para conferir cada rubrica.","Resolva todas as exceções com evidência.","Aprove os colaboradores e depois conclua o fechamento conforme o processo interno."], notes:["No ambiente externo, ações mutáveis são permitidas exclusivamente ao super_admin."] },
  { id:"terminations", title:"Desligamentos", path:"/desligamentos", purpose:"Coordenar cálculo rescisório, checklist, documentos e conclusão.", steps:["Abra o processo e confira modalidade, datas e cálculo.","Conclua as tarefas liberadas de cada área.","Resolva exceções que estejam bloqueando o checklist.","Revise a memória de cálculo e os documentos.","Aprove e conclua somente quando todas as tarefas estiverem finalizadas."] },
  { id:"documents", title:"Documentos", path:"/documentos", purpose:"Gerenciar documentos, modelos, validações e aceites eletrônicos.", steps:["Filtre documentos por tipo ou status.","Abra o documento para consultar metadados, validade e histórico.","Valide ou rejeite registrando uma observação.","Quando aplicável, registre o aceite eletrônico e confira a evidência gerada.","Use downloads temporários apenas para a finalidade autorizada."], notes:["Arquivos são privados e os acessos devem respeitar a finalidade e a LGPD."] },
  { id:"communications", title:"Comunicação", path:"/comunicacao", purpose:"Enviar comunicados e acompanhar notificações orientadas a eventos.", steps:["Escolha o público e o canal apropriado.","Use um modelo existente ou prepare o conteúdo.","Revise destinatários, texto e momento de envio.","Publique o comunicado e acompanhe entrega e leitura.","Investigue falhas ou duplicidades sinalizadas pelo sistema."] },
  { id:"analytics", title:"Indicadores", path:"/indicadores", purpose:"Analisar tendências, departamentos e relatórios gerenciais.", steps:["Selecione período e dimensão desejados.","Compare indicadores e variações relevantes.","Abra os insights para entender o contexto sugerido.","Valide os dados de origem antes de tomar decisões.","Gere relatórios quando precisar registrar ou compartilhar a análise."], notes:["Insights auxiliam a decisão, mas não substituem revisão humana."] },
  { id:"health", title:"Saúde ocupacional", path:"/saude-ocupacional", purpose:"Controlar exames, ASOs, riscos, programas e vencimentos.", steps:["Acompanhe exames pendentes e próximos do vencimento.","Abra o colaborador ou agenda para revisar riscos e requisitos.","Registre agendamento, resultado e situação do ASO.","Trate exceções e impedimentos antes da alocação.","Monitore programas e prazos recorrentes."], notes:["Dados de saúde são sensíveis e devem ser acessados somente por pessoas autorizadas."] },
  { id:"patrols", title:"Rondas e postos", path:"/rondas", purpose:"Executar rotas, leituras por QR Code e registro de ocorrências.", steps:["Escolha uma rota disponível e inicie a ronda.","Leia o QR Code em cada ponto previsto.","Registre uma ocorrência com descrição e evidência quando necessário.","Acompanhe cobertura e pontos faltantes na operação ao vivo.","Finalize a rota e trate ocorrências pendentes."], notes:["Não compartilhe tokens ou QR Codes operacionais fora das equipes autorizadas."] },
  { id:"workflows", title:"Automações", path:"/automacoes", purpose:"Acompanhar workflows, tarefas automáticas e intervenção humana.", steps:["Consulte fluxos ativos e a versão da definição.","Abra uma execução para visualizar etapas e histórico.","Conclua tarefas humanas atribuídas ao seu perfil.","Trate exceções antes de tentar avançar o fluxo.","Verifique na auditoria se a automação retomou corretamente."] },
  { id:"governance", title:"Configurações e governança", path:"/configuracoes", purpose:"Administrar usuários, papéis, permissões, auditoria e sessões.", steps:["Revise os usuários e seus papéis por organização.","Conceda somente as permissões necessárias para cada função.","Consulte sessões ativas e revogue acessos suspeitos com justificativa.","Use a auditoria para investigar alterações e decisões.","Revise periodicamente segregação de funções e acessos privilegiados."], notes:["O papel super_admin é restrito à administração da plataforma e às operações reais atualmente habilitadas."] },
];

const faq = [
  ["Por que não consigo editar ou aprovar uma operação?", "No ambiente externo, mutações são restritas ao super_admin. Confirme também se existem exceções abertas, tarefas bloqueadas ou campos obrigatórios pendentes."],
  ["Por que um colaborador não aparece na lista?", "Verifique a organização ativa, os filtros e se o colaborador possui vínculo ativo com empresa, estabelecimento, departamento e centro de custo."],
  ["Como sei se um cadastro é fictício?", "A massa de teste usa matrícula e documentos com o prefixo FICT, além de endereços de e-mail no domínio example.invalid."],
  ["Posso desfazer uma aprovação?", "Algumas decisões geram novas versões ou exigem um fluxo de correção. Consulte o histórico e a auditoria; não altere diretamente registros já consolidados."],
  ["O que devo escrever ao resolver uma exceção?", "Registre o que foi conferido, qual correção foi feita, a fonte da evidência e por que a operação pode continuar."],
  ["Qual a diferença entre alerta, tarefa e exceção?", "Alerta informa uma condição; tarefa representa trabalho a executar; exceção interrompe ou condiciona o fluxo até uma decisão ou correção."],
  ["Como funcionam os status?", "Em geral, pendente aguarda ação, em andamento está sendo processado, bloqueado depende de correção, aprovado foi validado e concluído encerra o fluxo. Cada módulo pode apresentar variações."],
  ["Os dados são salvos automaticamente?", "Consultas atualizam a tela automaticamente, mas formulários e decisões só são persistidos depois da confirmação explícita da ação."],
  ["Por que vejo números diferentes entre o painel e um módulo?", "O painel resume dados e pode usar períodos ou recortes diferentes. Confira filtros, competência e horário da última atualização no módulo de origem."],
  ["Como devo lidar com dados pessoais e documentos?", "Acesse somente o necessário para sua função, não copie dados para canais não autorizados e respeite retenção, sigilo e finalidade previstos pela LGPD."],
  ["O que fazer se a tela não carregar?", "Atualize a página, confirme sua conexão e sessão e tente novamente. Se persistir, registre o módulo, horário, ação realizada e mensagem exibida para o suporte."],
  ["Como sair com segurança?", "Use o botão Sair junto ao seu perfil no rodapé do menu lateral, especialmente em computadores compartilhados."],
] as const;

export function UserManualPage() {
  const [query, setQuery] = useState("");
  const normalized = query.trim().toLocaleLowerCase("pt-BR");
  const visibleSections = useMemo(() => sections.filter(section => !normalized || [section.title,section.purpose,...section.steps,...(section.notes??[])].join(" ").toLocaleLowerCase("pt-BR").includes(normalized)), [normalized]);
  const visibleFaq = useMemo(() => faq.filter(item => !normalized || item.join(" ").toLocaleLowerCase("pt-BR").includes(normalized)), [normalized]);

  return <div className="page manual-page">
    <section className="simple-heading manual-heading"><div><span className="eyebrow"><BookOpen/> Central de ajuda</span><h1>Manual do usuário</h1><p>Guia completo para operar o FluxRH com segurança, do cadastro à governança.</p></div></section>
    <div className="manual-search"><Search aria-hidden="true"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar funcionalidade ou dúvida" aria-label="Buscar no manual"/><span>{visibleSections.length} módulos</span></div>
    <div className="manual-layout">
      <aside className="manual-index" aria-label="Índice do manual"><strong>Neste manual</strong>{visibleSections.map(section=><a key={section.id} href={`#manual-${section.id}`}>{section.title}</a>)}<a href="#manual-faq">Perguntas frequentes</a></aside>
      <div className="manual-content">
        {visibleSections.map((section,index)=><article className="manual-section" id={`manual-${section.id}`} key={section.id}>
          <header><span>{String(index+1).padStart(2,"0")}</span><div><h2>{section.title}</h2><p>{section.purpose}</p></div><Link to={section.path}>Abrir módulo <ChevronRight/></Link></header>
          <h3>Como usar</h3><ol>{section.steps.map(step=><li key={step}>{step}</li>)}</ol>
          {section.notes?.length&&<div className="manual-note"><strong>Atenção</strong>{section.notes.map(note=><p key={note}>{note}</p>)}</div>}
        </article>)}
        <section className="manual-faq" id="manual-faq"><div className="faq-title"><CircleHelp/><div><h2>Perguntas frequentes</h2><p>Selecione uma pergunta para expandir a resposta.</p></div></div>{visibleFaq.map(([question,answer])=><details key={question}><summary>{question}<ChevronRight/></summary><p>{answer}</p></details>)}{!visibleSections.length&&!visibleFaq.length&&<div className="manual-empty">Nenhum conteúdo encontrado para “{query}”.</div>}</section>
      </div>
    </div>
  </div>;
}
